name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo 
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  Linter:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [Build]
    steps:
      - name: Download a single artifact # Name of the step
        uses: actions/download-artifact@v4 # Action to use
        with: # Parameters for the action
          name: my-artifact # Name of the artifact to download. Optional. If unspecified, all artifacts for the run are downloaded.
          path: path/to/download/artifact/     # Destination path. Supports basic tilde expansion.  # Optional. Default is $GITHUB_WORKSPACE
    
