name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'oh hey daniel'
        type: string
        required: true
        default: World
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: running
      - run: echo "Hello ${{ inputs.who-to-greet }} "
